[package]
name = "cmd-rs"
authors = ["pauliyobo <pauliyobo@gmail.com>"]
version = "0.1.0"
edition = "2018"
license = "MIT"

[dependencies]
rustyline = "9.0.0"
anyhow = "1.0.44"
cmd-rs-macro = { path = "cmd-rs-macro"}